/**
 * Deamon Backup API
 * Deamon used to periodically generate volume's backup and send of this backups
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['Backend/lib/doc-node-client/src/ApiClient', 'model/Backup', 'model/Container', 'model/ContainerHostConfig', 'model/ContainerNetworkSettings', 'model/EndpointIPAMConfig', 'model/EndpointSettings', 'model/Error', 'model/InlineResponse200', 'model/InlineResponse2001', 'model/InlineResponse2002', 'model/InlineResponse2003', 'model/Mount', 'model/MountBindOptions', 'model/MountTmpfsOptions', 'model/MountVolumeOptions', 'model/MountVolumeOptionsDriverConfig', 'model/Port', 'model/Volume', 'model/VolumeUsageData', 'api/ContainerApi', 'api/VolumeApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Backup'), require('./model/Container'), require('./model/ContainerHostConfig'), require('./model/ContainerNetworkSettings'), require('./model/EndpointIPAMConfig'), require('./model/EndpointSettings'), require('./model/Error'), require('./model/InlineResponse200'), require('./model/InlineResponse2001'), require('./model/InlineResponse2002'), require('./model/InlineResponse2003'), require('./model/Mount'), require('./model/MountBindOptions'), require('./model/MountTmpfsOptions'), require('./model/MountVolumeOptions'), require('./model/MountVolumeOptionsDriverConfig'), require('./model/Port'), require('./model/Volume'), require('./model/VolumeUsageData'), require('./api/ContainerApi'), require('./api/VolumeApi'));
  }
}(function(ApiClient, Backup, Container, ContainerHostConfig, ContainerNetworkSettings, EndpointIPAMConfig, EndpointSettings, Error, InlineResponse200, InlineResponse2001, InlineResponse2002, InlineResponse2003, Mount, MountBindOptions, MountTmpfsOptions, MountVolumeOptions, MountVolumeOptionsDriverConfig, Port, Volume, VolumeUsageData, ContainerApi, VolumeApi) {
  'use strict';

  /**
   * Deamon_used_to_periodically_generate_volumes_backup_and_send_of_this_backups.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var DeamonBackupApi = require('index'); // See note below*.
   * var xxxSvc = new DeamonBackupApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new DeamonBackupApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new DeamonBackupApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new DeamonBackupApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Backup model constructor.
     * @property {module:model/Backup}
     */
    Backup: Backup,
    /**
     * The Container model constructor.
     * @property {module:model/Container}
     */
    Container: Container,
    /**
     * The ContainerHostConfig model constructor.
     * @property {module:model/ContainerHostConfig}
     */
    ContainerHostConfig: ContainerHostConfig,
    /**
     * The ContainerNetworkSettings model constructor.
     * @property {module:model/ContainerNetworkSettings}
     */
    ContainerNetworkSettings: ContainerNetworkSettings,
    /**
     * The EndpointIPAMConfig model constructor.
     * @property {module:model/EndpointIPAMConfig}
     */
    EndpointIPAMConfig: EndpointIPAMConfig,
    /**
     * The EndpointSettings model constructor.
     * @property {module:model/EndpointSettings}
     */
    EndpointSettings: EndpointSettings,
    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error: Error,
    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200: InlineResponse200,
    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001: InlineResponse2001,
    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002: InlineResponse2002,
    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003: InlineResponse2003,
    /**
     * The Mount model constructor.
     * @property {module:model/Mount}
     */
    Mount: Mount,
    /**
     * The MountBindOptions model constructor.
     * @property {module:model/MountBindOptions}
     */
    MountBindOptions: MountBindOptions,
    /**
     * The MountTmpfsOptions model constructor.
     * @property {module:model/MountTmpfsOptions}
     */
    MountTmpfsOptions: MountTmpfsOptions,
    /**
     * The MountVolumeOptions model constructor.
     * @property {module:model/MountVolumeOptions}
     */
    MountVolumeOptions: MountVolumeOptions,
    /**
     * The MountVolumeOptionsDriverConfig model constructor.
     * @property {module:model/MountVolumeOptionsDriverConfig}
     */
    MountVolumeOptionsDriverConfig: MountVolumeOptionsDriverConfig,
    /**
     * The Port model constructor.
     * @property {module:model/Port}
     */
    Port: Port,
    /**
     * The Volume model constructor.
     * @property {module:model/Volume}
     */
    Volume: Volume,
    /**
     * The VolumeUsageData model constructor.
     * @property {module:model/VolumeUsageData}
     */
    VolumeUsageData: VolumeUsageData,
    /**
     * The ContainerApi service constructor.
     * @property {module:api/ContainerApi}
     */
    ContainerApi: ContainerApi,
    /**
     * The VolumeApi service constructor.
     * @property {module:api/VolumeApi}
     */
    VolumeApi: VolumeApi
  };

  return exports;
}));
