/**
 * Deamon Backup API
 * Deamon used to periodically generate volume's backup and send of this backups
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DeamonBackupApi) {
      root.DeamonBackupApi = {};
    }
    root.DeamonBackupApi.Backup = factory(root.DeamonBackupApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Backup model module.
   * @module model/Backup
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Backup</code>.
   * @alias module:model/Backup
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Backup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Backup} obj Optional instance to populate.
   * @return {module:model/Backup} The populated <code>Backup</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('containerName')) {
        obj['containerName'] = ApiClient.convertToType(data['containerName'], 'String');
      }
      if (data.hasOwnProperty('backupName')) {
        obj['backupName'] = ApiClient.convertToType(data['backupName'], 'String');
      }
      if (data.hasOwnProperty('createdAt')) {
        obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
      }
      if (data.hasOwnProperty('hostname')) {
        obj['hostname'] = ApiClient.convertToType(data['hostname'], 'String');
      }
    }
    return obj;
  }

  /**
   * Name of the container backuped
   * @member {String} containerName
   */
  exports.prototype['containerName'] = undefined;
  /**
   * Name of the backup file
   * @member {String} backupName
   */
  exports.prototype['backupName'] = undefined;
  /**
   * Date/Time the backup was created.
   * @member {String} createdAt
   */
  exports.prototype['createdAt'] = undefined;
  /**
   * Host from where the backup was created.
   * @member {String} hostname
   */
  exports.prototype['hostname'] = undefined;



  return exports;
}));


