/**
 * Deamon Backup API
 * Deamon used to periodically generate volume's backup and send of this backups
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EndpointIPAMConfig'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EndpointIPAMConfig'));
  } else {
    // Browser globals (root is window)
    if (!root.DeamonBackupApi) {
      root.DeamonBackupApi = {};
    }
    root.DeamonBackupApi.EndpointSettings = factory(root.DeamonBackupApi.ApiClient, root.DeamonBackupApi.EndpointIPAMConfig);
  }
}(this, function(ApiClient, EndpointIPAMConfig) {
  'use strict';




  /**
   * The EndpointSettings model module.
   * @module model/EndpointSettings
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>EndpointSettings</code>.
   * Configuration for a network endpoint.
   * @alias module:model/EndpointSettings
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>EndpointSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EndpointSettings} obj Optional instance to populate.
   * @return {module:model/EndpointSettings} The populated <code>EndpointSettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('IPAMConfig')) {
        obj['IPAMConfig'] = EndpointIPAMConfig.constructFromObject(data['IPAMConfig']);
      }
      if (data.hasOwnProperty('Links')) {
        obj['Links'] = ApiClient.convertToType(data['Links'], ['String']);
      }
      if (data.hasOwnProperty('Aliases')) {
        obj['Aliases'] = ApiClient.convertToType(data['Aliases'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/EndpointIPAMConfig} IPAMConfig
   */
  exports.prototype['IPAMConfig'] = undefined;
  /**
   * @member {Array.<String>} Links
   */
  exports.prototype['Links'] = undefined;
  /**
   * @member {Array.<String>} Aliases
   */
  exports.prototype['Aliases'] = undefined;



  return exports;
}));


