/**
 * Deamon Backup API
 * Deamon used to periodically generate volume's backup and send of this backups
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DeamonBackupApi) {
      root.DeamonBackupApi = {};
    }
    root.DeamonBackupApi.EndpointIPAMConfig = factory(root.DeamonBackupApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EndpointIPAMConfig model module.
   * @module model/EndpointIPAMConfig
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>EndpointIPAMConfig</code>.
   * EndpointIPAMConfig represents an endpoint&#39;&#39;s IPAM configuration.
   * @alias module:model/EndpointIPAMConfig
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>EndpointIPAMConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EndpointIPAMConfig} obj Optional instance to populate.
   * @return {module:model/EndpointIPAMConfig} The populated <code>EndpointIPAMConfig</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('IPv4Address')) {
        obj['IPv4Address'] = ApiClient.convertToType(data['IPv4Address'], 'String');
      }
      if (data.hasOwnProperty('IPv6Address')) {
        obj['IPv6Address'] = ApiClient.convertToType(data['IPv6Address'], 'String');
      }
      if (data.hasOwnProperty('LinkLocalIPs')) {
        obj['LinkLocalIPs'] = ApiClient.convertToType(data['LinkLocalIPs'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} IPv4Address
   */
  exports.prototype['IPv4Address'] = undefined;
  /**
   * @member {String} IPv6Address
   */
  exports.prototype['IPv6Address'] = undefined;
  /**
   * @member {Array.<String>} LinkLocalIPs
   */
  exports.prototype['LinkLocalIPs'] = undefined;



  return exports;
}));


