/**
 * Deamon Backup API
 * Deamon used to periodically generate volume's backup and send of this backups
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DeamonBackupApi) {
      root.DeamonBackupApi = {};
    }
    root.DeamonBackupApi.MountVolumeOptionsDriverConfig = factory(root.DeamonBackupApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MountVolumeOptionsDriverConfig model module.
   * @module model/MountVolumeOptionsDriverConfig
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MountVolumeOptionsDriverConfig</code>.
   * Map of driver specific options
   * @alias module:model/MountVolumeOptionsDriverConfig
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>MountVolumeOptionsDriverConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MountVolumeOptionsDriverConfig} obj Optional instance to populate.
   * @return {module:model/MountVolumeOptionsDriverConfig} The populated <code>MountVolumeOptionsDriverConfig</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('Options')) {
        obj['Options'] = ApiClient.convertToType(data['Options'], {'String': 'String'});
      }
    }
    return obj;
  }

  /**
   * Name of the driver to use to create the volume.
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * key/value map of driver specific options.
   * @member {Object.<String, String>} Options
   */
  exports.prototype['Options'] = undefined;



  return exports;
}));


