/**
 * Deamon Backup API
 * Deamon used to periodically generate volume's backup and send of this backups
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MountVolumeOptionsDriverConfig'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MountVolumeOptionsDriverConfig'));
  } else {
    // Browser globals (root is window)
    if (!root.DeamonBackupApi) {
      root.DeamonBackupApi = {};
    }
    root.DeamonBackupApi.MountVolumeOptions = factory(root.DeamonBackupApi.ApiClient, root.DeamonBackupApi.MountVolumeOptionsDriverConfig);
  }
}(this, function(ApiClient, MountVolumeOptionsDriverConfig) {
  'use strict';




  /**
   * The MountVolumeOptions model module.
   * @module model/MountVolumeOptions
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MountVolumeOptions</code>.
   * Optional configuration for the &#x60;volume&#x60; type.
   * @alias module:model/MountVolumeOptions
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>MountVolumeOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MountVolumeOptions} obj Optional instance to populate.
   * @return {module:model/MountVolumeOptions} The populated <code>MountVolumeOptions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('NoCopy')) {
        obj['NoCopy'] = ApiClient.convertToType(data['NoCopy'], 'Boolean');
      }
      if (data.hasOwnProperty('Labels')) {
        obj['Labels'] = ApiClient.convertToType(data['Labels'], {'String': 'String'});
      }
      if (data.hasOwnProperty('DriverConfig')) {
        obj['DriverConfig'] = MountVolumeOptionsDriverConfig.constructFromObject(data['DriverConfig']);
      }
    }
    return obj;
  }

  /**
   * Populate volume with data from the target.
   * @member {Boolean} NoCopy
   * @default false
   */
  exports.prototype['NoCopy'] = false;
  /**
   * User-defined key/value metadata.
   * @member {Object.<String, String>} Labels
   */
  exports.prototype['Labels'] = undefined;
  /**
   * @member {module:model/MountVolumeOptionsDriverConfig} DriverConfig
   */
  exports.prototype['DriverConfig'] = undefined;



  return exports;
}));


