/**
 * Deamon Backup API
 * Deamon used to periodically generate volume's backup and send of this backups
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DeamonBackupApi) {
      root.DeamonBackupApi = {};
    }
    root.DeamonBackupApi.MountTmpfsOptions = factory(root.DeamonBackupApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MountTmpfsOptions model module.
   * @module model/MountTmpfsOptions
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MountTmpfsOptions</code>.
   * Optional configuration for the &#x60;tmpfs&#x60; type.
   * @alias module:model/MountTmpfsOptions
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>MountTmpfsOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MountTmpfsOptions} obj Optional instance to populate.
   * @return {module:model/MountTmpfsOptions} The populated <code>MountTmpfsOptions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('SizeBytes')) {
        obj['SizeBytes'] = ApiClient.convertToType(data['SizeBytes'], 'Number');
      }
      if (data.hasOwnProperty('Mode')) {
        obj['Mode'] = ApiClient.convertToType(data['Mode'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The size for the tmpfs mount in bytes.
   * @member {Number} SizeBytes
   */
  exports.prototype['SizeBytes'] = undefined;
  /**
   * The permission mode for the tmpfs mount in an integer.
   * @member {Number} Mode
   */
  exports.prototype['Mode'] = undefined;



  return exports;
}));


