/**
 * Deamon Backup API
 * Deamon used to periodically generate volume's backup and send of this backups
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DeamonBackupApi);
  }
}(this, function(expect, DeamonBackupApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DeamonBackupApi.Container();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Container', function() {
    it('should create an instance of Container', function() {
      // uncomment below and update the code to test Container
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be.a(DeamonBackupApi.Container);
    });

    it('should have the property id (base name: "Id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

    it('should have the property names (base name: "Names")', function() {
      // uncomment below and update the code to test the property names
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

    it('should have the property image (base name: "Image")', function() {
      // uncomment below and update the code to test the property image
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

    it('should have the property imageID (base name: "ImageID")', function() {
      // uncomment below and update the code to test the property imageID
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

    it('should have the property command (base name: "Command")', function() {
      // uncomment below and update the code to test the property command
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "Created")', function() {
      // uncomment below and update the code to test the property created
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

    it('should have the property ports (base name: "Ports")', function() {
      // uncomment below and update the code to test the property ports
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

    it('should have the property sizeRw (base name: "SizeRw")', function() {
      // uncomment below and update the code to test the property sizeRw
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

    it('should have the property sizeRootFs (base name: "SizeRootFs")', function() {
      // uncomment below and update the code to test the property sizeRootFs
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

    it('should have the property labels (base name: "Labels")', function() {
      // uncomment below and update the code to test the property labels
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "State")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "Status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

    it('should have the property hostConfig (base name: "HostConfig")', function() {
      // uncomment below and update the code to test the property hostConfig
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

    it('should have the property networkSettings (base name: "NetworkSettings")', function() {
      // uncomment below and update the code to test the property networkSettings
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

    it('should have the property mounts (base name: "Mounts")', function() {
      // uncomment below and update the code to test the property mounts
      //var instance = new DeamonBackupApi.Container();
      //expect(instance).to.be();
    });

  });

}));
