/**
 * Deamon Backup API
 * Deamon used to periodically generate volume's backup and send of this backups
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DeamonBackupApi);
  }
}(this, function(expect, DeamonBackupApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DeamonBackupApi.Mount();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Mount', function() {
    it('should create an instance of Mount', function() {
      // uncomment below and update the code to test Mount
      //var instance = new DeamonBackupApi.Mount();
      //expect(instance).to.be.a(DeamonBackupApi.Mount);
    });

    it('should have the property target (base name: "Target")', function() {
      // uncomment below and update the code to test the property target
      //var instance = new DeamonBackupApi.Mount();
      //expect(instance).to.be();
    });

    it('should have the property source (base name: "Source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new DeamonBackupApi.Mount();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "Type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new DeamonBackupApi.Mount();
      //expect(instance).to.be();
    });

    it('should have the property readOnly (base name: "ReadOnly")', function() {
      // uncomment below and update the code to test the property readOnly
      //var instance = new DeamonBackupApi.Mount();
      //expect(instance).to.be();
    });

    it('should have the property consistency (base name: "Consistency")', function() {
      // uncomment below and update the code to test the property consistency
      //var instance = new DeamonBackupApi.Mount();
      //expect(instance).to.be();
    });

    it('should have the property bindOptions (base name: "BindOptions")', function() {
      // uncomment below and update the code to test the property bindOptions
      //var instance = new DeamonBackupApi.Mount();
      //expect(instance).to.be();
    });

    it('should have the property volumeOptions (base name: "VolumeOptions")', function() {
      // uncomment below and update the code to test the property volumeOptions
      //var instance = new DeamonBackupApi.Mount();
      //expect(instance).to.be();
    });

    it('should have the property tmpfsOptions (base name: "TmpfsOptions")', function() {
      // uncomment below and update the code to test the property tmpfsOptions
      //var instance = new DeamonBackupApi.Mount();
      //expect(instance).to.be();
    });

  });

}));
